baseurl: /
languageCode: en-us
title: DaydreamEdu
theme: "ghostwriter"
googleAnalytics: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
params:
  mainSections:
    - post
  intro: true
  description: "DaydreamEdu is a venture to evolve better and more humane education for everyone."
